#!/bin/sh


if [ -n "$1" ]; then
  cd "$1"
fi
wd=$(pwd)

set -eu
cd $(dirname "$0")

export DOCKER_BUILDKIT=1
export USER=$(whoami)

if [ ! -f "tensorflow-1.15.5-cp36-cp36m-linux_x86_64.whl" ]; then
  echo "No local tensorflow cache file, building it (this will take a while)"
  cd tensorflow
  docker build -t video-anon:tensorflow .
  cd ..

  docker create --name="tmp_$$" video-anon:tensorflow fakecmd
  docker export tmp_$$ | tar x --wildcards '*.whl'
  docker rm tmp_$$
fi

docker build -t video-anon:runner-cpu .

echo "\n\n"
cd $wd

extra=""
if [ -t 1 ]; then
  extra="--tty"
fi

docker run -i $extra --rm --name video-anon-cpu \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  --mount type=bind,source=$(pwd),target=/data \
  --mount type=tmpfs,destination=/tmp \
  video-anon:runner-cpu
