#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [ -n "$1" ]; then
  cd "$1"
fi
wd=$(pwd)

set -eu
cd $SCRIPT_DIR

export DOCKER_BUILDKIT=1
export USER=$(whoami)

docker build -t video-anon:runner-gpu .

echo -e "\n\n"
cd $wd

extra=""
if [ -t 1 ]; then
  extra="--tty"
fi

docker run -i $extra --rm --name video-anon-gpu \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  --gpus all \
  --mount type=bind,source=$(pwd),target=/data \
  --mount type=tmpfs,destination=/tmp \
  video-anon:runner-gpu
